//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.06 at 04:24:38 PM CEST 
//


package com.mikalai.touristvouchers_jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for extendedVoucher complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="extendedVoucher"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://example.com/TouristVouchers}voucher"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hotel" type="{http://example.com/TouristVouchers}ExtendedHotelCharacteristic"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extendedVoucher", propOrder = {
        "hotel"
})
public class ExtendedVoucher
        extends Voucher
{

    @XmlElement(required = true)
    protected ExtendedHotelCharacteristic hotel;

    /**
     * Gets the value of the hotel property.
     *
     * @return
     *     possible object is
     *     {@link ExtendedHotelCharacteristic }
     *
     */
    public ExtendedHotelCharacteristic getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     *
     * @param value
     *     allowed object is
     *     {@link ExtendedHotelCharacteristic }
     *
     */
    public void setHotel(ExtendedHotelCharacteristic value) {
        this.hotel = value;
    }

}
