//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.06 at 04:24:38 PM CEST 
//


package com.mikalai.touristvouchers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotelCharacteristic complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HotelCharacteristic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stars" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="mealIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mealType" type="{http://example.com/TouristVouchers}Meal"/&gt;
 *         &lt;element name="roomType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tvIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="acIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelCharacteristic", propOrder = {
        "stars",
        "mealIncluded",
        "mealType",
        "roomType",
        "tvIncluded",
        "acIncluded"
})
@XmlSeeAlso({
        ExtendedHotelCharacteristic.class
})
public class HotelCharacteristic {

    protected int stars;
    protected boolean mealIncluded;
    @XmlElement(required = true, defaultValue = "BB")
    @XmlSchemaType(name = "string")
    protected Meal mealType;
    @XmlElement(required = true)
    protected String roomType;
    protected boolean tvIncluded;
    protected boolean acIncluded;

    /**
     * Gets the value of the stars property.
     *
     */
    public int getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     *
     */
    public void setStars(int value) {
        this.stars = value;
    }

    /**
     * Gets the value of the mealIncluded property.
     *
     */
    public boolean isMealIncluded() {
        return mealIncluded;
    }

    /**
     * Sets the value of the mealIncluded property.
     *
     */
    public void setMealIncluded(boolean value) {
        this.mealIncluded = value;
    }

    /**
     * Gets the value of the mealType property.
     *
     * @return
     *     possible object is
     *     {@link Meal }
     *
     */
    public Meal getMealType() {
        return mealType;
    }

    /**
     * Sets the value of the mealType property.
     *
     * @param value
     *     allowed object is
     *     {@link Meal }
     *
     */
    public void setMealType(Meal value) {
        this.mealType = value;
    }

    /**
     * Gets the value of the roomType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRoomType(String value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the tvIncluded property.
     *
     */
    public boolean isTvIncluded() {
        return tvIncluded;
    }

    /**
     * Sets the value of the tvIncluded property.
     *
     */
    public void setTvIncluded(boolean value) {
        this.tvIncluded = value;
    }

    /**
     * Gets the value of the acIncluded property.
     *
     */
    public boolean isAcIncluded() {
        return acIncluded;
    }

    /**
     * Sets the value of the acIncluded property.
     *
     */
    public void setAcIncluded(boolean value) {
        this.acIncluded = value;
    }

}
