//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.06 at 04:24:38 PM CEST 
//


package com.mikalai.touristvouchers;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.touristvouchers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.touristvouchers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TouristVouchers }
     * 
     */
    public TouristVouchers createTouristVouchers() {
        return new TouristVouchers();
    }

    /**
     * Create an instance of {@link StandardVoucher }
     * 
     */
    public StandardVoucher createStandardVoucher() {
        return new StandardVoucher();
    }

    /**
     * Create an instance of {@link ExtendedVoucher }
     * 
     */
    public ExtendedVoucher createExtendedVoucher() {
        return new ExtendedVoucher();
    }

    /**
     * Create an instance of {@link HotelCharacteristic }
     * 
     */
    public HotelCharacteristic createHotelCharacteristic() {
        return new HotelCharacteristic();
    }

    /**
     * Create an instance of {@link ExtendedHotelCharacteristic }
     * 
     */
    public ExtendedHotelCharacteristic createExtendedHotelCharacteristic() {
        return new ExtendedHotelCharacteristic();
    }

}
